# build orthanc server - done
# orthanc-with-plugins-enabled - done
# add POSTGRESQL Support - done
# integrate with OHIF viewer - done
# nginx deployment - done
# add pgadmin for postgres - done
# tests and healthchecks

version: "3.8"
services:
  orthanc-container:
    image: orthancteam/orthanc:24.7.3
    restart: unless-stopped
    volumes:
      - orthanc-storage:/var/lib/orthanc/db/
    environment:
      ORTHANC__NAME: "OHIF in container"

      DICOM_WEB_PLUGIN_ENABLED: "true"
      ORTHANC__DICOM_WEB__PUBLIC_ROOT: "/orthanc-container/dicom-web/"

      ORTHANC__ORTHANC_EXPLORER_2__UI_OPTIONS__ENABLE_OPEN_IN_OHIF_VIEWER_3: "true"
      ORTHANC__ORTHANC_EXPLORER_2__UI_OPTIONS__OHIF_VIEWER_3_PUBLIC_ROOT: "http://localhost/ohif/"

      ORTHANC__AUTHENTICATION_ENABLED: "false"
      ORTHANC__POSTGRESQL: |
        {
          "Host": "orthanc-index"
        }

      VERBOSE_STARTUP: "true"

  orthanc-plugin:
    image: orthancteam/orthanc:24.7.3
    restart: unless-stopped
    ports:
      - 8053:8042
    volumes:
      - orthanc-storage:/var/lib/orthanc/db/
    environment:
      ORTHANC__NAME: "OHIF in container"

      DICOM_WEB_PLUGIN_ENABLED: "true"
      ORTHANC__DICOM_WEB__PUBLIC_ROOT: "/orthanc-plugin/dicom-web/"

      ORTHANC__ORTHANC_EXPLORER_2__UI_OPTIONS__ENABLE_OPEN_IN_OHIF_VIEWER_3: "true"
      ORTHANC__ORTHANC_EXPLORER_2__UI_OPTIONS__OHIF_VIEWER_3_PUBLIC_ROOT: "http://localhost/orthanc-plugin/ohif/"

      STONE_WEB_VIEWER_PLUGIN_ENABLED: "true"

      OHIF_PLUGIN_ENABLED: "true"
      ORTHANC__OHIF: |
        {
          "RouterBasename": "/orthanc-plugin/ohif/",
          "DataSource" : "dicom-web"
        }

      ORTHANC__AUTHENTICATION_ENABLED: "false"
      ORTHANC__POSTGRESQL: |
        {
          "Host": "orthanc-index"
        }

      VERBOSE_STARTUP: "true"

  ohif:
    # container_name: ohif-viewer-prototype
    # image: ohif/viewer
    build: ohif
    # optional if you want to customize the OHIF configuration:
    volumes:
      - ./ohif/default-app-config.js:/usr/share/nginx/html/app-config.js:ro
      - ./logo.png:/usr/share/nginx/html/logo.png:ro
    restart: unless-stopped
    depends_on:
      - orthanc-container

  orthanc-index:
    image: postgres:15
    restart: unless-stopped
    ports: ["5432:5432"]
    volumes: ["orthanc-index:/var/lib/postgresql/data"]
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5051:5051"

  nginx:
    # build: nginx
    image: nginx:latest
    container_name: nginx-container
    volumes:
      - ./nginx/:/etc/nginx/conf.d
    restart: unless-stopped
    ports:
      - 80:80
    depends_on:
      - orthanc-container
      - orthanc-plugin
      - ohif

volumes:
  orthanc-storage:
  orthanc-index:
